[package]
name = "patisson-binance-sdk"
version = "0.1.9"
edition = "2024"
authors = ["Yurii Musolov <yurii.musolov@gmail.com>"]
description = "Unofficial Rust SDK for the Binance exchange API"
keywords = ["binance", "sdk", "crypto", "trading", "cryptocurrency"]
categories = ["api-bindings", "cryptography::cryptocurrencies"]
documentation = "https://docs.rs/crate/patisson-binance-sdk"
repository = "https://github.com/yurii-musolov/patisson-binance-sdk"
license = "MIT"
readme = "README.md"
include = [
  "/src/**/*",
  "/examples/**/*",
  "/Cargo.toml",
  "/README.md",
  "/LICENSE",
]

[lib]
name = "binance"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.104"
futures = "0.3.34"
futures-util = { version = "0.3.34", default-features = false, features = [
  "sink",
  "std",
] }
hex = "0.4.3"
hmac = "0.13.0"
reqwest = { version = "0.13.4", features = ["json", "query"] }
rust_decimal = { version = "1.42.1", features = [
  "std",
  "macros",
  "serde-str",
  "serde-with-str",
] }
serde = { version = "1.0.229", features = ["derive"] }
serde-aux = "4.7"
serde_json = "1.0.151"
serde_path_to_error = "0.1.20"
serde_repr = "0.1.21"
serde_urlencoded = "0.7.1"
sha2 = "0.11.0"
thiserror = "2.0.20"
tokio = { version = "1.52.3", features = ["full"] }
tokio-tungstenite = { version = "0.30.0", features = ["native-tls"] }
tokio-util = "0.7.19"
tracing = "0.1.44"
tungstenite = "0.30.0"

[dev-dependencies]
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
