[package]
name = "examples"
version.workspace = true
edition.workspace = true
authors.workspace = true
publish = false

[[example]]
name = "exchange-info"
path = "exchange-info.rs"

[[example]]
name = "kline"
path = "kline.rs"

[[example]]
name = "server-time"
path = "server-time.rs"
