[package]
name = "examples"
version.workspace = true
edition.workspace = true
authors.workspace = true
publish = false

[[example]]
name = "account-information"
path = "account-information.rs"

[[example]]
name = "exchange-info"
path = "exchange-info.rs"

[[example]]
name = "kline"
path = "kline.rs"

[[example]]
name = "query-order"
path = "query-order.rs"

[[example]]
name = "server-time"
path = "server-time.rs"

[[example]]
name = "stream-public"
path = "stream-public.rs"

[[example]]
name = "test-new-order"
path = "test-new-order.rs"

[[example]]
name = "ticker-statistics"
path = "ticker-statistics.rs"
