[package]
name = "examples"
version.workspace = true
edition.workspace = true
authors.workspace = true
publish = false

# Spot
[[example]]
name = "spot-account-information"
path = "spot-account-information.rs"

[[example]]
name = "spot-exchange-info"
path = "spot-exchange-info.rs"

[[example]]
name = "spot-kline"
path = "spot-kline.rs"

[[example]]
name = "spot-query-order"
path = "spot-query-order.rs"

[[example]]
name = "spot-server-time"
path = "spot-server-time.rs"

[[example]]
name = "spot-stream-public"
path = "spot-stream-public.rs"

[[example]]
name = "spot-test-new-order"
path = "spot-test-new-order.rs"

[[example]]
name = "spot-ticker-statistics"
path = "spot-ticker-statistics.rs"

# USDⓈ-M Futures
[[example]]
name = "usdm-account-information"
path = "usdm-account-information.rs"

[[example]]
name = "usdm-exchange-info"
path = "usdm-exchange-info.rs"

[[example]]
name = "usdm-kline"
path = "usdm-kline.rs"

[[example]]
name = "usdm-server-time"
path = "usdm-server-time.rs"

[[example]]
name = "usdm-stream-public"
path = "usdm-stream-public.rs"

# Margin
[[example]]
name = "margin-account"
path = "margin-account.rs"

[[example]]
name = "margin-max-borrowable"
path = "margin-max-borrowable.rs"

# COIN-M Futures
[[example]]
name = "coinm-account-information"
path = "coinm-account-information.rs"

[[example]]
name = "coinm-exchange-info"
path = "coinm-exchange-info.rs"

[[example]]
name = "coinm-kline"
path = "coinm-kline.rs"

[[example]]
name = "coinm-server-time"
path = "coinm-server-time.rs"

[[example]]
name = "coinm-stream-public"
path = "coinm-stream-public.rs"
